/*
    In this question, I wrote a program to find the super digit of a number X generated by n and k;
    Name and Surname : Feyzullah Asıllıoğlu
    Student ID : 150121021
*/
#include <stdio.h>

__int64 concat(int, int);
__int64 getExponent(int, int);
int getMaxDigitValue(__int64);
int getSuperDigit(__int64);

int main(int argc, char const *argv[])
{
    int number, k;
    __int64 concatinatedNumber;
    printf("%s", "Please enter a number (n=) : ");
    scanf("%d", &number);
    printf("%s", "Please enter repetition factor (k=) : ");
    scanf("%d", &k);
    // the maximum number of digits of the concatinatedNumber is 19
    // If you exceed the limit, the number will be incorrect
    concatinatedNumber = concat(number, k);
    printf("%s %lld %s %d", "Super digit of number", concatinatedNumber, "is", getSuperDigit(concatinatedNumber));

    return 0;
}

int getMaxDigitValue(__int64 number)
{
    int maxDigitValue = 0;
    for (int i = 0; number >= 1; i++)
    {
        number /= 10;
        maxDigitValue++;
    }
    return maxDigitValue;
}

__int64 concat(int number, int k)
{
    __int64 concatinatedNumber = number;
    int tempN = number,
        maxDigitValue = getMaxDigitValue(number);

    for (int j = 1; j < k; j++)
    {
        concatinatedNumber *= getExponent(10, maxDigitValue);
        concatinatedNumber += number;
    }
    return concatinatedNumber;
}

__int64 getExponent(int number, int maxDigitValue)
{
    if (maxDigitValue == 1)
    {
        return 10;
    }
    return number * getExponent(number, maxDigitValue - 1);
}

int getSuperDigit(__int64 concatinatedNumber)
{
    int superDigit = 0,
        digit = 0,
        maxDigitValue = getMaxDigitValue(concatinatedNumber);

    for (int i = 0; i < maxDigitValue; i++)
    {
        digit = concatinatedNumber % 10;
        superDigit += digit;
        concatinatedNumber /= 10;
    }
    return superDigit;
}